<?php
use think\facade\Route;
Route::rule("userLogin","Login/login","GET");
Route::rule("index","Index/index","GET");
// Route::rule("md","Login/md","GET");
// Route::rule("md","AdminBase/getSession","GET");
Route::rule("vrtrain","VrTrain/vrtrain","GET");
Route::rule("vrtrainList","VrTrain/vrtrainList","GET");
Route::rule("vrexam","VrExam/vrexam","GET");
Route::rule("vrexamList","VrExam/vrexamList","GET");
Route::rule("artrain","ArTrain/artrain","GET");
Route::rule("artrainList","ArTrain/artrainList","GET");
Route::rule("arexam","ArExam/arexam","GET");
Route::rule("arexamList","ArExam/arexamList","GET");
Route::rule("logout","Logout/index","GET");
Route::rule("runother","RunOther/runother","GET");
Route::rule("getall","RunOther/getAll","GET");
Route::rule("checkip","RunOther/checkIp","POST");
Route::rule("loginCheck","Login/check","POST");
Route::rule("register","Login/register","POST");